### ISSUE TITLE
grayscale image colorization

### ISSUE THREAD

**Issue by cyanymore** [ZhenglinPan/LCMFTN-pytorch#2]
Thank you very much for reproducing the code! I want to ask you how I should handle coloring a grayscale image if I want to use a visible image as a reference, what do I need to do? Thank you very much for your answer!

**Comment by zhenglinpan** [comment]
> Thank you very much for reproducing the code! I want to ask you how I should handle coloring a grayscale image if I want to use a visible image as a reference, what do I need to do? Thank you very much for your answer!

Hi :) 

If I understand you correctly, you are trying to colorize a grayscale image given a chromatic reference image.

LCMFTN is designed for propagating color between frames for Animation specifically, I don't think it works for single grayscale images. 

That said, you can check the repo AwesomeAnimeResearch [here](https://github.com/SerialLain3170/AwesomeAnimeResearch) for further paper references in Anime Illustrations, there're a bunch of researches you may be interested in, including colorization.

For colorizing grayscaled images in general domain, you can try look for unsupervised or referenced-based image colorization paperworks. 

Hope this would help you.

**Comment by cyanymore** [comment]
Thank you very much for your help!
